### Index 
GET http://localhost:3000/products.json 

### Show 
GET http://localhost:3000/products/2.json

### Create
POST http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg4Mzg1MTF9.3yOx9Cif23ool3gme4Ap1KwuE34kq4ZJ5VY1GtEp9rg
Content-Type: application/json

{"name": "Apple",
"price": 2,
"image_url": "nvwkg",
"description": "Makes your skin smooth"
}

### Update 
PATCH http://localhost:3000/products/4.json 
Content-Type: application/json

{"name":"Ice",
"price": "3",
"image_url": "dfsd",
"description": "Frozen water"
}



### Delete
DELETE http://localhost:3000/products/3.json

### User Create (aka Sign-Up)
POST http://localhost:3000/users.json
Content-Type: application/json

{"name": "Marlo",
"email": "marloboyer@test.com",
"password": "password",
"password_confirmation": "password"
}

### Session Create (aka Login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{"email": "marloboyer@test.com",
"password": "password"}

### Orders Create 
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg5MzQ2MTd9.x2VhAzC75XjAOBwJ-wTvMaSThxP1W-pFzU0cD0ebfYs
Content-Type: application/json

{
"product_id":4, 
"quantity": 4

}

### Orders Show 
GET http://localhost:3000/orders/4.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg5MzQ2MTd9.x2VhAzC75XjAOBwJ-wTvMaSThxP1W-pFzU0cD0ebfYs

### Orders Index 
GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg5MzQ2MTd9.x2VhAzC75XjAOBwJ-wTvMaSThxP1W-pFzU0cD0ebfYs
